### ISSUE TITLE
Accordion Secion Size

### ISSUE THREAD

**Issue by bhofner** [leifoolsen/mdl-ext#42]
Hello Leif,

I played a bit with your accordion - nice work.
While in your examples the opend accordion sections are just big enough to contain their respective content, I somehow managed to create an accordion that always opens its section to the bottom of the browser window. Is there a way to influence this bevaviour deterministically?

Best regards, Bernd

**Comment by leifoolsen** [comment]
Hello Bernd,

Thank you for trying out the accordion. We have not started to use it in production yet, so there may be snags :)
If you do not set **aria-multiselectable=true**, the accordion must have it's dimensions restricted by an outer container. By default, the accordion has width=100% and height=100%. If this does not solve your problem, please provide some example code, I'm more than happy to help out.

Regards Leif
