### ISSUE TITLE
Minified CSS doesn't render down-arrow on selectfields

### ISSUE THREAD

**Issue by mbirth** [leifoolsen/mdl-ext#48]
When using `lib/mdl-ext.min.css` (from 0.8.12), the down arrows are missing from selectfields. Using `lib/mdl-ext.css`, they render as expected. Tested in Chrome.

**Comment by leifoolsen** [comment]
@mbirth Thanks for spotting that. The `border-top-color: inherit` has disappeared during minifying (maybe a bug in WebPack?). Will see if I can get around this problem, possibly by  setting a specified color, like the disabled version of the select element has.
