### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by EinarJohnsen** [leifoolsen/mdl-ext#67]
$mdlext-accordion-content-background-color is never used in the code. It should set the background color of the content of a tab and it should be laid under .mdlext-accordion__panel__content.
It should also have a variable for the color of the text. 

Should also probably be renamed to something with tab-panel. 

Otherwise :+1:

**Comment by leifoolsen** [comment]
$mdlext-accordion-content-background-color is used in mdlext-accordion__tabpanel, but variable to set a default font color is missing.
