### ISSUE TITLE
Accordion - mer som kan fikses

### ISSUE THREAD

**Issue by EinarJohnsen** [leifoolsen/mdl-ext#68]
Når du har et disabled felt, har dette fremdeles musepeker som de som kan klikkes på. Denne bør endres til standard musepeker.

I tillegg kan et disabled felt også trykkes, og får en outline. Jeg mener det bør unngås da det kan gi en feil oppfatning, hvis det kan få fokus.

**Comment by leifoolsen** [comment]
Har du verifisert at dette stemmer i siste versjon, 0.9.20?
